language: rust
rust:
  - stable
  - beta
  - nightly

services:
  - docker

os:
  - linux

matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - wget
      - zsh

script:
  - cargo build --verbose
  - cargo test --verbose
before_deploy: "bash package.sh"
deploy:
  provider: releases
  api_key:
    secure: VVO5do0l1H5cpW3l/bhYjk1W3qCPzWA0qGHWD4lQ7hgN4+vdRZZeujZPh++THrLbtUCKZC3Wy69czW8fFw3lUn7ZUOE41oH0maOp+WLoElwVqYamQA4np3/yWv+A/QimqeD3B8fW+cK1fs5touRWrtvfOmCarhtwbs/bkDPRMNX5z2sV8BH9PlLKBUhkzfoipfiTLPbAuepmdOSfuD35b2whZHR3kqrjlkJ/TKlvzYu7DMoeWJiGbyq6D4pjNM4m34m/1Jfsly+9tTwF0zUnaDLpLXMDGeu/W7ztC3A0lHmgPdFrkV07iSYxi4ILEHwEH+1eWT7aIM5X3jGq7CR2S5ykCawzwSzZv4Kqq5JiJlU7mNeJOxn82vwtoe83lbNIeRwaZgDaePCOQJzBYUFi5zzag9qqB2R6HSTFP4y935JeO60YXbe5c0ZlU3jmwKMDssEcSWg6+Rk2VojVgDvWrUSc4zr6clzTonES1loljxTvVrydSxt9WBJsSt0ydvevWiBV1IxlqLpSq/cfZrDnEyqGLd835h9caybrh5ne7ty+ncyLOe3xc4vIWUIkZU9Ccf1DnJb/h5GLdDbMvjOwmebmSe5w4XhemIWGpE83DDmjFpaFtd742lNOHcHvjixZQiz0X7P27JfrDFA4q05avBATt654miRkgk1qtXMz2rw=
  file:
    - "./target/x86_64-unknown-linux-musl/release/fblog"
    - "./target/x86_64-unknown-linux-musl/release/fblog.deb"
    - "./target/x86_64-unknown-linux-musl/release/fblog.rpm"
  on:
    tags: true
    rust: stable

notifications:
  email:
    on_success: never
    on_failure: always
