[package]
name = "fblog"
version = "0.1.4"
authors = ["Patrick Haun <bomgar85@googlemail.com>"]
license = "WTFPL"
categories = ["command-line-utilities"]
description = "json log viewer"
keywords = ["json", "log", "viewer" ]
repository = "https://github.com/brocode/fblog"
readme = "README.org"

[dependencies]
serde_json = "1.0"
clap = "2.22"
ansi_term = "0.9"
